apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-core
  template:
    metadata:
      labels:
        app: bank-core
    spec:
      containers:
        - name: bank-core
          image: bereketab24/bank-core:v0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:postgresql://ledger-db-primary:5432/ledger-db
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: bank-kafka-kafka-bootstrap.kafka.svc:9092
            - name: RABBITMQ_HOST
              value: rabbitmq.rabbitmq.svc
          resources:
            requests:
              cpu: 300m
              memory: 384Mi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: actuator/health/readiness
              port: 8080
