controller:
  serviceType: NodePort
  servicePort: 8080
  nodePort: 32000
  resources:
    limits:
      cpu: 600m
      memory: 1200Mi
    requests:
      cpu: 300m
      memory: 768Mi
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - pipeline-stage-view:latest
    - docker-workflow:latest
    - gradle:latest
    - configuration-as-code:latest
  initContainers:
    - name: volume-permissions-fix
      image: busybox:latest
      command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
persistence:
  enabled: true
  storageClass: jenkins-pv
  size: 3Gi
serviceAccount:
  create: false
  name: jenkins
