auth:
  username: guest
  password: guest #use k8s secret in prod

image:
  registry: docker.io
  repository: bitnamilegacy/rabbitmq
  tag: 4.1.3-debian-12-r1
replicaCount: 1
persistence:
  enabled: true
  storageClass: "standard"
  size: 1Gi
extraConfiguration: |
  load_definitions = /app/load_definitions.json
extraSecrets: {}
metrics:
  enabled: true