apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-core
  template:
    metadata:
      labels:
        app: bank-core
    spec:
      containers:
        - name: app
          image: nginx:alpine
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: bank-core
spec:
  selector:
    app: bank-core
  ports:
    - port: 80
      targetPort: 80
